apiVersion: v1
kind: Pod
metadata:
  name: startup-pod
  namespace: probes

spec:
  containers:
  - name: startup-container
    image: nginx

    startupProbe:
      httpGet:
        path: /
        port: 80

      failureThreshold: 30
      periodSeconds: 5

